resolver: ghc-9.10.1  # Tell Stack to use system-installed GHC

packages:
  - .

extra-deps:

flags: {}

extra-package-dbs: []

ghc-options:
  "$everything": -Wall

system-ghc: false
compiler: ghc-9.10.1
compiler-check: match-exact
